# Generated by Django 4.1.9 on 2023-05-27 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('numero_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=100)),
                ('prenom_client', models.CharField(max_length=100)),
                ('email_client', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id_manager', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voitures',
            fields=[
                ('id_voiture', models.AutoField(primary_key=True, serialize=False)),
                ('nom_voiture', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('N', 'Not Reserved'), ('R', 'Reserved')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id_reservation', models.AutoField(primary_key=True, serialize=False)),
                ('date_reservation', models.DateField()),
                ('status_reservation', models.CharField(choices=[('A', 'accepted'), ('R', 'rejected')], max_length=1)),
                ('id_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.manager')),
                ('id_voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.voitures')),
                ('numero_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.client')),
            ],
        ),
    ]
